// AUTO-GENERATED by scripts/build-schema-migrations.ts from src/core/schema-migrations/v<NNN>-*.ts.
// Do not edit or hand-merge. Regenerate: bun run build:schema-migrations
//
// Schema migrations (database DDL, applied by src/core/migrate.ts runMigrations and
// recorded in schema_version). Not to be confused with the version-upgrade
// orchestrator registry in src/commands/migrations/index.ts.

import type { Migration } from './types.ts';
import { v002 } from './v002-slugify-existing-pages.ts';
import { v003 } from './v003-unique-chunk-index.ts';
import { v004 } from './v004-access-tokens-and-mcp-log.ts';
import { v005 } from './v005-minion-jobs-table.ts';
import { v006 } from './v006-agent-orchestration-primitives.ts';
import { v007 } from './v007-agent-parity-layer.ts';
import { v008 } from './v008-multi-type-links-constraint.ts';
import { v009 } from './v009-timeline-dedup-index.ts';
import { v010 } from './v010-drop-timeline-search-trigger.ts';
import { v011 } from './v011-links-provenance-columns.ts';
import { v012 } from './v012-budget-ledger.ts';
import { v013 } from './v013-minion-quiet-hours-stagger.ts';
import { v014 } from './v014-pages-updated-at-index.ts';
import { v015 } from './v015-minion-jobs-max-stalled-default-5.ts';
import { v016 } from './v016-cycle-locks-table.ts';
import { v020 } from './v020-sources-table-additive.ts';
import { v021 } from './v021-pages-source-id-composite-unique.ts';
import { v022 } from './v022-links-resolution-type.ts';
import { v023 } from './v023-files-source-id-page-id-ledger.ts';
import { v024 } from './v024-rls-backfill-missing-tables.ts';
import { v025 } from './v025-pages-page-kind.ts';
import { v026 } from './v026-content-chunks-code-metadata.ts';
import { v027 } from './v027-cathedral-ii-foundation.ts';
import { v028 } from './v028-cathedral-ii-chunk-fts-backfill.ts';
import { v029 } from './v029-cathedral-ii-code-edges-rls.ts';
import { v030 } from './v030-dream-verdicts-table.ts';
import { v031 } from './v031-eval-capture-tables.ts';
import { v032 } from './v032-oauth-infrastructure.ts';
import { v033 } from './v033-admin-dashboard-columns-v0-26-3.ts';
import { v034 } from './v034-destructive-guard-columns.ts';
import { v035 } from './v035-auto-rls-event-trigger.ts';
import { v036 } from './v036-subagent-provider-neutral-persistence-v0-27.ts';
import { v037 } from './v037-takes-and-synthesis-evidence.ts';
import { v038 } from './v038-access-tokens-permissions.ts';
import { v039 } from './v039-multimodal-dual-column-v0-27-1.ts';
import { v040 } from './v040-pages-emotional-weight.ts';
import { v041 } from './v041-pages-recency-columns.ts';
import { v042 } from './v042-eval-candidates-recency-capture.ts';
import { v043 } from './v043-takes-resolved-quality-and-drift-decisions.ts';
import { v044 } from './v044-pages-emotional-weight-recomputed-at.ts';
import { v045 } from './v045-facts-hot-memory-v0-31.ts';
import { v046 } from './v046-mcp-request-log-params-jsonb-normalize.ts';
import { v047 } from './v047-facts-notability-alter.ts';
import { v048 } from './v048-takes-weight-round-to-grid.ts';
import { v049 } from './v049-eval-takes-quality-runs.ts';
import { v050 } from './v050-ingest-log-source-id.ts';
import { v051 } from './v051-facts-fence-columns.ts';
import { v052 } from './v052-eval-contradictions-cache.ts';
import { v053 } from './v053-eval-contradictions-runs.ts';
import { v054 } from './v054-cjk-wave-pages-chunker-version-and-source-path.ts';
import { v055 } from './v055-query-cache-search-lite.ts';
import { v056 } from './v056-query-cache-knobs-hash.ts';
import { v057 } from './v057-search-telemetry-rollup.ts';
import { v058 } from './v058-edges-backfilled-at-v0-33-2.ts';
import { v059 } from './v059-code-traversal-cache-v0-34.ts';
import { v060 } from './v060-oauth-clients-source-id-fk.ts';
import { v061 } from './v061-oauth-clients-federated-read-column.ts';
import { v062 } from './v062-oauth-clients-federated-read-backfill.ts';
import { v063 } from './v063-oauth-clients-federated-read-validate.ts';
import { v064 } from './v064-oauth-clients-source-id-fk-restrict.ts';
import { v065 } from './v065-oauth-clients-federated-read-gin-index.ts';
import { v066 } from './v066-embed-stale-partial-index.ts';
import { v067 } from './v067-facts-typed-claim-columns.ts';
import { v068 } from './v068-calibration-profiles-v0-36.ts';
import { v069 } from './v069-take-proposals-v0-36.ts';
import { v070 } from './v070-take-grade-cache-v0-36.ts';
import { v071 } from './v071-take-nudge-log-v0-36.ts';
import { v072 } from './v072-takes-resolved-at-trend-idx-v0-36.ts';
import { v073 } from './v073-think-ab-results-v0-36.ts';
import { v074 } from './v074-eval-candidates-embedding-column.ts';
import { v075 } from './v075-op-checkpoints-table.ts';
import { v076 } from './v076-minion-jobs-doctor-run-id-index.ts';
import { v077 } from './v077-mcp-spend-log.ts';
import { v078 } from './v078-embedding-multimodal-column.ts';
import { v079 } from './v079-pages-last-retrieved-at.ts';
import { v080 } from './v080-takes-unresolvable-quality-v0-37-2-0.ts';
import { v081 } from './v081-pages-provenance-columns.ts';
import { v082 } from './v082-subagent-tool-executions-stable-id.ts';
import { v083 } from './v083-mcp-spend-reservations.ts';
import { v084 } from './v084-oauth-clients-budget-usd-per-day.ts';
import { v085 } from './v085-oauth-clients-agent-binding.ts';
import { v086 } from './v086-page-links-view-alias.ts';
import { v087 } from './v087-takes-kind-drop-check.ts';
import { v088 } from './v088-eval-candidates-schema-pack-per-source.ts';
import { v089 } from './v089-facts-event-type-column.ts';
import { v090 } from './v090-contextual-retrieval-columns.ts';
import { v091 } from './v091-pages-generation-trigger-and-bookmark.ts';
import { v092 } from './v092-sources-github-repo-index.ts';
import { v093 } from './v093-minions-v0-41-audit-and-budget.ts';
import { v094 } from './v094-take-domain-assignments.ts';
import { v095 } from './v095-links-link-source-check-includes-mentions.ts';
import { v096 } from './v096-facts-extract-conversation-session-index.ts';
import { v097 } from './v097-pages-dedup-partial-index.ts';
import { v098 } from './v098-gbrain-cycle-locks-last-refreshed-at.ts';
import { v099 } from './v099-conversation-parser-llm-cache-table.ts';
import { v101 } from './v101-links-link-kind-column.ts';
import { v102 } from './v102-timeline-entries-source-in-dedup.ts';
import { v103 } from './v103-migration-impact-log-and-priority-recent-idx.ts';
import { v104 } from './v104-pages-atom-source-hash-idx.ts';
import { v105 } from './v105-slug-aliases.ts';
import { v106 } from './v106-extract-rollup-7d-table.ts';
import { v107 } from './v107-page-generation-clock-and-statement-trigger.ts';
import { v108 } from './v108-pages-embedding-signature.ts';
import { v109 } from './v109-sources-newest-content-at.ts';
import { v110 } from './v110-page-aliases.ts';
import { v111 } from './v111-search-telemetry-rank1-columns.ts';
import { v112 } from './v112-pages-links-extracted-at.ts';
import { v113 } from './v113-links-link-source-widen-for-wikilink-basename.ts';
import { v114 } from './v114-links-link-source-check-kebab-regex.ts';
import { v115 } from './v115-op-checkpoint-paths-append-table.ts';
import { v116 } from './v116-code-edges-source-backfill-and-callee-index.ts';
import { v117 } from './v117-context-volunteer-events-table.ts';
import { v118 } from './v118-page-generation-clock-sequence-swap.ts';
import { v119 } from './v119-op-checkpoints-completed-keys-array-check.ts';
import { v120 } from './v120-schema-lint-hardening-search-path-security-invoker.ts';
import { v121 } from './v121-timeline-entries-event-page-id.ts';
import { v122 } from './v122-facts-ontology-dimension.ts';
import { v123 } from './v123-configurable-fts-language.ts';
import { v124 } from './v124-page-search-vector-drop-compiled-truth.ts';
import { v125 } from './v125-take-proposals-per-claim-idempotency.ts';
import { v126 } from './v126-session-context-state.ts';
import { v127 } from './v127-oauth-client-surface-and-minion-queue-index.ts';
import { v128 } from './v128-minion-jobs-timeout-backfill-and-duplicate-cycle-cleanup.ts';
import { v129 } from './v129-dream-verdicts-triage-v1-columns.ts';
import { v130 } from './v130-minion-jobs-lock-duration-ms.ts';
import { v131 } from './v131-drop-job-wide-subagent-tool-use-id-unique.ts';
import { v132 } from './v132-session-context-state-checkpoint-manifest.ts';
import { v133 } from './v133-content-chunks-embedded-text-hash.ts';
import { v134 } from './v134-restore-chunks-embedding-null-partial-indexes.ts';
import { v135 } from './v135-facts-event-time-index.ts';
import { v136 } from './v136-minion-private-queue-owner-metadata.ts';
import { v137 } from './v137-entity-identities.ts';
import { v138 } from './v138-timeline-dedup-md5-summary.ts';
import { v139 } from './v139-timeline-legacy-source-split-repair.ts';
import { v140 } from './v140-chat-usage-log.ts';
import { v141 } from './v141-extract-rollup-expected-limit.ts';
import { v142 } from './v142-takes-embedding-dimension-matches-config.ts';
import { v143 } from './v143-dream-verdicts-ttl.ts';
import { v144 } from './v144-open-loops.ts';
import { v145 } from './v145-facts-kind-idea-alter.ts';
import { v146 } from './v146-extract-atoms-transcript-state-table.ts';
import { v147 } from './v147-oauth-client-capability-grants.ts';
import { v148 } from './v148-durable-fact-withdrawals.ts';
import { v149 } from './v149-minion-submission-authority.ts';
import { v150 } from './v150-canonical-page-revisions-and-guards.ts';
import { v151 } from './v151-durable-concurrent-persistence.ts';
import { v152 } from './v152-unique-lock-acquisition-tokens.ts';
import { v153 } from './v153-verified-text-projection-activation.ts';
import { v154 } from './v154-preserve-sanitized-page-search-vectors.ts';
import { v155 } from './v155-recoverable-postcommit-persistence-effects.ts';
import { v156 } from './v156-managed-alias-and-source-checkpoint-guards.ts';
import { v157 } from './v157-recoverable-source-topology.ts';
import { v158 } from './v158-canonical-version-deletion-state.ts';
import { v159 } from './v159-index-retained-publication-recovery.ts';
import { v160 } from './v160-current-text-projection-planner-statistics.ts';
import { v161 } from './v161-index-pending-text-projections.ts';
import { v162 } from './v162-source-ingestion-receipts-with-policy.ts';
import { v163 } from './v163-derived-atom-page-scan-state.ts';
import { v164 } from './v164-shared-brain-skills-and-membership.ts';
import { v165 } from './v165-index-database-only-pending-writes.ts';
import { v166 } from './v166-fact-embedding-identity.ts';
import { v167 } from './v167-facts-superseded-by-set-null.ts';
import { v168 } from './v168-dream-synthesis-completions.ts';
import { v169 } from './v169-fact-withdrawal-subject.ts';
import { v170 } from './v170-index-parked-persistence-effects.ts';
import { v171 } from './v171-content-chunks-embedding-input-hash.ts';
import { v172 } from './v172-pages-safe-chunk-pending-index.ts';
import { v173 } from './v173-minion-jobs-dead-subagent-finished-index.ts';
import { v174 } from './v174-fact-withdrawal-normalized-fingerprint.ts';
import { v175 } from './v175-tags-tag-source.ts';
import { v176 } from './v176-connector-checkpoint-stable-identity.ts';
import { v177 } from './v177-pages-database-only-reason.ts';
import { v178 } from './v178-persistence-writer-version-stamps.ts';
import { v179 } from './v179-persistence-request-sync-run-indexes.ts';
import { v180 } from './v180-pages-links-attendance-blocked.ts';
import { v181 } from './v181-connector-dispatch-attempts.ts';
import { v182 } from './v182-page-versions-source-path.ts';
import { v183 } from './v183-persistence-mode-epoch.ts';
import { v184 } from './v184-decision-receipts.ts';
import { v185 } from './v185-decide-calibrations.ts';
import { v186 } from './v186-decide-proposals.ts';
import { v187 } from './v187-fact-relink-attempts.ts';
import { v188 } from './v188-facts-ontology-stint-dedup.ts';
import { v189 } from './v189-pages-credential-projection-pending.ts';
import { v190 } from './v190-sources-upstream-observation.ts';
import { v191 } from './v191-alias-source-cascade.ts';
import { v192 } from './v192-take-embedding-identity.ts';
import { v193 } from './v193-f1-write-attribution.ts';
import { v194 } from './v194-f0-worktree-refreshes.ts';
import { v195 } from './v195-f3-access-token-grants.ts';
import { v196 } from './v196-f4-planner-stats.ts';
import { v197 } from './v197-managed-guard-null-source-fallback.ts';
import { v198 } from './v198-publication-failure-detail.ts';
import { v199 } from './v199-chronicle-page-state.ts';
import { v200 } from './v200-sync-hold-page-index.ts';
import { v201 } from './v201-persistence-graduation.ts';
import { v202 } from './v202-legacy-token-grant-conversion.ts';
import { v203 } from './v203-oauth-client-grant-axes.ts';
import { v204 } from './v204-links-temporal-state.ts';
import { v205 } from './v205-minion-spend-authorization.ts';
import { v206 } from './v206-entity-mention-index.ts';
import { v207 } from './v207-retrieval-feedback.ts';
import { v208 } from './v208-facts-attributed-to.ts';

// Array order is historical (see HISTORICAL_ARRAY_ORDER in the generator); the
// runner sorts by version before applying.
export const MIGRATIONS: Migration[] = [
  v002,
  v003,
  v004,
  v005,
  v006,
  v007,
  v008,
  v009,
  v010,
  v011,
  v012,
  v013,
  v014,
  v023,
  v022,
  v021,
  v020,
  v015,
  v016,
  v024,
  v025,
  v026,
  v027,
  v028,
  v029,
  v037,
  v038,
  v030,
  v031,
  v032,
  v033,
  v034,
  v035,
  v036,
  v039,
  v040,
  v041,
  v042,
  v043,
  v044,
  v045,
  v046,
  v047,
  v048,
  v049,
  v050,
  v051,
  v052,
  v053,
  v054,
  v059,
  v058,
  v055,
  v056,
  v057,
  v060,
  v061,
  v062,
  v063,
  v064,
  v065,
  v078,
  v077,
  v066,
  v067,
  v068,
  v069,
  v070,
  v071,
  v072,
  v073,
  v074,
  v075,
  v076,
  v079,
  v080,
  v081,
  v082,
  v083,
  v084,
  v085,
  v086,
  v087,
  v088,
  v089,
  v090,
  v091,
  v092,
  v093,
  v094,
  v095,
  v096,
  v097,
  v098,
  v099,
  v101,
  v102,
  v103,
  v104,
  v105,
  v106,
  v107,
  v108,
  v109,
  v110,
  v111,
  v112,
  v113,
  v114,
  v115,
  v116,
  v117,
  v118,
  v119,
  v120,
  v121,
  v122,
  v123,
  v124,
  v125,
  v126,
  v127,
  v128,
  v129,
  v130,
  v131,
  v132,
  v133,
  v134,
  v135,
  v136,
  v137,
  v138,
  v139,
  v140,
  v141,
  v142,
  v143,
  v144,
  v145,
  v146,
  v147,
  v148,
  v149,
  v150,
  v151,
  v152,
  v153,
  v154,
  v155,
  v156,
  v157,
  v158,
  v159,
  v160,
  v161,
  v162,
  v163,
  v164,
  v165,
  v166,
  v167,
  v168,
  v169,
  v170,
  v171,
  v172,
  v173,
  v174,
  v175,
  v176,
  v177,
  v178,
  v179,
  v180,
  v181,
  v182,
  v183,
  v184,
  v185,
  v186,
  v187,
  v188,
  v189,
  v190,
  v191,
  v192,
  v193,
  v194,
  v195,
  v196,
  v197,
  v198,
  v199,
  v200,
  v201,
  v202,
  v203,
  v204,
  v205,
  v206,
  v207,
  v208,
];
